# ─────────────────────────────────────────────
# TLS Key Pair — generated by Terraform, private
# key saved locally, public key registered in AWS
# ─────────────────────────────────────────────

resource "tls_private_key" "bastion" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "bastion" {
  key_name   = "${var.project_name}-bastion-key"
  public_key = tls_private_key.bastion.public_key_openssh

  tags = merge(var.common_tags, {
    Name = "${var.project_name}-bastion-key"
  })
}

# Save private key to local disk
# chmod 400 is set so only owner can read (required for SSH)
resource "local_file" "private_key" {
  content         = tls_private_key.bastion.private_key_pem
  filename        = "${path.module}/${var.project_name}-bastion.pem"
  file_permission = "0400"
}
